### ISSUE TITLE
`master` to `main` branch

### ISSUE THREAD

**Issue by Lextuga007** [MLCSU/MLCSUr#1]
Would it be ok to move the branch name to `main`? These slides can help as they detail how to use the {usethis} package 🙂  https://intro-git-github.nhsrcommunity.com/session-setup.html#/master-or-main

**Comment by ScottJohnson2** [comment]
I would say go ahead. Is this just a naming convention thing? I.e. there is no change in functionality?

**Comment by Lextuga007** [comment]
No change to functionality, it's a nicer convention because of its history as a reference to the slave trade https://www.jumpingrivers.com/blog/git-moving-master-to-main/. 

For practice can I assign this to you? Thanks

**Comment by ScottJohnson2** [comment]
Thanks Zoe, yes i would love the practice. For additional practice, i will attempt to assign to myself :-)

**Comment by Lextuga007** [comment]
This might help with the workflow too https://the-strategy-unit.github.io/data_science/style/git_and_github.html#create-a-branch and we welcome feedback, particularly if anything doesn't make sense.

**Comment by ScottJohnson2** [comment]
I think i have completed the task, certainly the name seems to have changed from master to main. Im not sure i have done all of the branching correctly though. First of all i created a branch within GitHub on the web browser as suggested by this doc: https://the-strategy-unit.github.io/data_science/style/git_and_github.html#create-a-branch
However, when i then couldnt figure out how to connect to this branch directly through usethis package, the instructions in the first link you share seemed to be the code needed to run only. With googling, I got as far as:

create_from_github('MLCSU/MLCSUr')

pr_init(branch = '1-master-to-main-branch')

git_default_branch_rename(from = "master", to = "main")

git_default_branch_configure()

pr_push()

I think the second line of code may have creaed another branch rather than connecting to the one i created earlier, and both branches seem to still exist despite the pr_push()

Any advice appreciated

**Comment by Lextuga007** [comment]
This is really helpful for me as I didn't make it clear that a change of name to the master > main branch is distinctly different to a "branch" being created from those! The workflow is confusing in this situation but you did it even with my added confusion 🚀 😀 

Possibly nobody else has a copy of this repository but if they have, they'll now get a prompt on GitHub to use the following code:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
on the Terminal (not the Console where R code is typed in RStudio) and that will update their local master branch to main to be in line with this remote version (you might need to do this yourself). 

This comment can be closed now. Also, as you have a branch there are slides detailing how to tidy up https://intro-git-github.nhsrcommunity.com/session-pull-requests.html#/finish-with-the-pr. 

Nice work!

**Comment by ScottJohnson2** [comment]
Thanks for your help and glad i was able to be of help to you too (even if accidentally)
